version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6.20
    environment:
      PGADMIN_DEFAULT_EMAIL: myuser@mail.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data:
